[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-lc++", "-C", "link-arg=-framework", "-C", "link-arg=Accelerate"]

[env]
MACOSX_DEPLOYMENT_TARGET = "10.15"
CMAKE_OSX_DEPLOYMENT_TARGET = "10.15"
